CREATE TABLE IF NOT EXISTS cliente (
 codigo SERIAL NOT NULL PRIMARY KEY,
 nome VARCHAR(150) NOT NULL,
 email VARCHAR(150) NOT NULL,
 cpf VARCHAR(20) NOT NULL,
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);